wip

diff --git a/.github/workflows/ca-clone-sequential-test.yml b/.github/workflows/ca-clone-sequential-test.yml
--- a/.github/workflows/ca-clone-sequential-test.yml
+++ b/.github/workflows/ca-clone-sequential-test.yml
@@ -96,6 +96,194 @@ jobs:
           # restart primary CA
           docker exec primary pki-server ca-redeploy --wait
 
+      - name: Install admin cert in primary CA
+        run: |
+          docker exec primary pki-server cert-export \
+              --cert-file $SHARED/ca_signing.crt \
+              ca_signing
+
+          docker exec primary pki nss-cert-import \
+              --cert $SHARED/ca_signing.crt \
+              --trust CT,C,C \
+              ca_signing
+
+          docker exec primary pki pkcs12-import \
+              --pkcs12 /root/.dogtag/pki-tomcat/ca_admin_cert.p12 \
+              --pkcs12-password Secret.123
+
+      - name: Check requests
+        if: always()
+        run: |
+          docker exec primary pki-server ca-cert-request-find | tee output
+          sed -n "s/^ *Request ID: *\(.*\)$/\1/p" output > actual
+
+          # there should be 6 requests
+          seq 1 6 > expected
+
+          diff expected actual
+
+      - name: Check certs
+        if: always()
+        run: |
+          docker exec primary pki-server ca-cert-find | tee output
+          sed -n "s/^ *Serial Number: *\(.*\)$/\1/p" output > actual
+
+          # there should be 6 certs
+          seq 1 6 | while read n; do printf "0x%x\n" $n; done > expected
+
+          diff expected actual
+
+      - name: Check request range config in primary CA
+        if: always()
+        run: |
+          docker exec primary pki-server ca-config-find \
+              | grep \
+                  -e dbs.beginRequestNumber \
+                  -e dbs.endRequestNumber \
+                  -e dbs.requestCloneTransferNumber \
+                  -e dbs.requestIncrement \
+                  -e dbs.requestLowWaterMark \
+              | tee actual
+
+          # request range should be 1 - 10 decimal (total: 10, remaining: 4)
+          cat > expected << EOF
+          dbs.beginRequestNumber=1
+          dbs.endRequestNumber=10
+          dbs.requestCloneTransferNumber=5
+          dbs.requestIncrement=10
+          dbs.requestLowWaterMark=5
+          EOF
+
+          diff expected actual
+
+      - name: Check cert range config in primary CA
+        if: always()
+        run: |
+          docker exec primary pki-server ca-config-find \
+              | grep \
+                  -e dbs.beginSerialNumber \
+                  -e dbs.endSerialNumber \
+                  -e dbs.serialCloneTransferNumber \
+                  -e dbs.serialIncrement \
+                  -e dbs.serialLowWaterMark \
+              | tee actual
+
+          # cert range should be 1 - 12 hex (total: 18, remaining: 12)
+          cat > expected << EOF
+          dbs.beginSerialNumber=1
+          dbs.endSerialNumber=12
+          dbs.serialCloneTransferNumber=9
+          dbs.serialIncrement=12
+          dbs.serialLowWaterMark=9
+          EOF
+
+          diff expected actual
+
+      - name: Check request repository
+        if: always()
+        run: |
+          docker exec primaryds ldapsearch \
+              -H ldap://primaryds.example.com:3389 \
+              -D "cn=Directory Manager" \
+              -w Secret.123 \
+              -b ou=ca,ou=requests,dc=ca,dc=pki,dc=example,dc=com \
+              -s base \
+              -o ldif_wrap=no \
+              -LLL | tee output
+
+          grep \
+              -e serialno: \
+              -e nextRange: \
+              output \
+              | sort > actual
+
+          # request nextRange should be dbs.beginRequestNumber incremented by
+          # 10 decimal to 21 decimal
+          cat > expected << EOF
+          nextRange: 21
+          serialno: 010
+          EOF
+
+          diff expected actual
+
+      - name: Check cert repository
+        if: always()
+        run: |
+          docker exec primaryds ldapsearch \
+              -H ldap://primaryds.example.com:3389 \
+              -D "cn=Directory Manager" \
+              -w Secret.123 \
+              -b ou=certificateRepository,ou=ca,dc=ca,dc=pki,dc=example,dc=com \
+              -s base \
+              -o ldif_wrap=no \
+              -LLL | tee output
+
+          grep \
+              -e serialno: \
+              -e nextRange: \
+              output \
+              | sort > actual
+
+          # cert nextRange should be dbs.beginSerialNumber incremented by 12 hex
+          # (18 decimal) to 13 hex (19 decimal), but currently the value will be
+          # processed as 13 decimal in:
+          # - Repository.getNextRange()
+          # - SubsystemRangeUpdateCLI.updateSerialNumberRange()
+          cat > expected << EOF
+          nextRange: 13
+          serialno: 011
+          EOF
+
+          diff expected actual
+
+      - name: Check request range objects
+        if: always()
+        run: |
+          docker exec primaryds ldapsearch \
+              -H ldap://primaryds.example.com:3389 \
+              -D "cn=Directory Manager" \
+              -w Secret.123 \
+              -b ou=requests,ou=ranges,dc=ca,dc=pki,dc=example,dc=com \
+              -s one \
+              -o ldif_wrap=no \
+              -LLL | tee output
+
+          grep \
+              -e SecurePort: \
+              -e beginRange: \
+              -e endRange: \
+              -e host: \
+              output \
+              | sort > actual
+
+          # new request range should be 11 - 20 decimal (total: 10)
+          cat > expected << EOF
+          SecurePort: 8443
+          beginRange: 11
+          endRange: 20
+          host: primary.example.com
+          EOF
+
+          diff expected actual
+
+      - name: Check cert range objects
+        if: always()
+        run: |
+          docker exec primaryds ldapsearch \
+              -H ldap://primaryds.example.com:3389 \
+              -D "cn=Directory Manager" \
+              -w Secret.123 \
+              -b ou=certificateRepository,ou=ranges,dc=ca,dc=pki,dc=example,dc=com \
+              -s one \
+              -o ldif_wrap=no \
+              -LLL | tee output
+
+          # there should be no new cert range
+          diff /dev/null output
+
+      ####################################################################################################
+      # Create secondary CA with Sequential Serial Numbers
+      #
       - name: Set up secondary DS container
         run: |
           tests/bin/ds-create.sh \
@@ -116,10 +304,6 @@ jobs:
 
       - name: Create secondary CA
         run: |
-          docker exec primary pki-server cert-export \
-              --cert-file $SHARED/ca_signing.crt \
-              ca_signing
-
           docker exec primary pki-server ca-clone-prepare \
               --pkcs12-file $SHARED/ca-certs.p12 \
               --pkcs12-password Secret.123
@@ -155,17 +339,6 @@ jobs:
 
           # restart secondary CA
           docker exec secondary pki-server ca-redeploy --wait
-
-      - name: Install admin cert in primary CA
-        run: |
-          docker exec primary pki nss-cert-import \
-              --cert $SHARED/ca_signing.crt \
-              --trust CT,C,C \
-              ca_signing
-
-          docker exec primary pki pkcs12-import \
-              --pkcs12 /root/.dogtag/pki-tomcat/ca_admin_cert.p12 \
-              --pkcs12-password Secret.123
 
       - name: Install admin cert in secondary CA
         run: |
@@ -240,6 +413,7 @@ jobs:
               | tee actual
 
           # request range should be 16 - 20 decimal (total: 5, remaining: 5)
+          # this range was split from the primary CA's range
           cat > expected << EOF
           dbs.beginRequestNumber=16
           dbs.endRequestNumber=20
@@ -263,6 +437,7 @@ jobs:
               | tee actual
 
           # cert range should be 1 - 9 hex (total: 9, remaining: 2)
+          # this range was split for secondary CA
           cat > expected << EOF
           dbs.beginSerialNumber=1
           dbs.endSerialNumber=9
@@ -286,6 +461,7 @@ jobs:
               | tee actual
 
           # cert range should be a - 12 hex (total: 9, remaining: 9)
+          # this range was split from primary CA
           cat > expected << EOF
           dbs.beginSerialNumber=a
           dbs.endSerialNumber=12
@@ -314,7 +490,7 @@ jobs:
               output \
               | sort > actual
 
-          # request nextRange should be the same
+          # request nextRange should be incremented by 10 decimal to 21 decimal
           cat > expected << EOF
           nextRange: 21
           serialno: 010
@@ -368,7 +544,7 @@ jobs:
               output \
               | sort > actual
 
-          # new request range should be 11 - 20 decimal (total: 10)
+          # request range should be the same
           cat > expected << EOF
           SecurePort: 8443
           beginRange: 11
@@ -395,25 +571,12 @@ jobs:
 
       ####################################################################################################
       # Enroll certs to exhaust request and cert ranges
-
-      - name: Enroll 5 certs in secondary CA
-        run: |
-          docker exec secondary pki \
-              nss-cert-request \
-              --subject "uid=testuser" \
-              --ext /usr/share/pki/tools/examples/certs/testuser.conf \
-              --csr testuser.csr
-
-          for i in $(seq 1 5); do
-              docker exec secondary pki \
-                  -n caadmin \
-                  ca-cert-issue \
-                  --profile caUserCert \
-                  --csr-file testuser.csr \
-                  --output-file testuser.crt
-
-              docker exec secondary openssl x509 -in testuser.crt -serial -noout
-          done
+      #
+      # This will create 2 requests and 2 certs in the primary CA,
+      # so there's no remaining certs in the current range.
+      #
+      # This will create 5 requests and 5 certs in the secondary CA,
+      # so there's no remaining requests in the current range.
 
       - name: Enroll 2 cert in primary CA
         if: always()
@@ -435,6 +598,25 @@ jobs:
               docker exec primary openssl x509 -in testuser.crt -serial -noout
           done
 
+      - name: Enroll 5 certs in secondary CA
+        run: |
+          docker exec secondary pki \
+              nss-cert-request \
+              --subject "uid=testuser" \
+              --ext /usr/share/pki/tools/examples/certs/testuser.conf \
+              --csr testuser.csr
+
+          for i in $(seq 1 5); do
+              docker exec secondary pki \
+                  -n caadmin \
+                  ca-cert-issue \
+                  --profile caUserCert \
+                  --csr-file testuser.csr \
+                  --output-file testuser.crt
+
+              docker exec secondary openssl x509 -in testuser.crt -serial -noout
+          done
+
       - name: Check requests
         if: always()
         run: |
@@ -442,9 +624,8 @@ jobs:
           sed -n "s/^ *Request ID: *\(.*\)$/\1/p" output > actual
 
           # there should be 14 requests
-          seq 1 7 > expected
+          seq 1 9 > expected
           seq 16 20 >> expected
-          seq 8 9 >> expected
 
           diff expected actual
 
@@ -650,6 +831,28 @@ jobs:
 
       ####################################################################################################
       # Enroll a cert when request range is exhausted
+      #
+      # Enrollment on primary CA will fail due to exhausted cert range, but
+      # it will create a new request.
+      #
+      # Enrollment on secondary CA will fail due to exhausted request range.
+
+      - name: Enroll a cert when cert range is exhausted
+        run: |
+          docker exec primary pki \
+              -n caadmin \
+              ca-cert-issue \
+              --profile caUserCert \
+              --csr-file testuser.csr \
+              --output-file testuser.crt \
+              > >(tee stdout) 2> >(tee stderr >&2) || true
+
+          cat > expected << EOF
+          PKIException: Server Internal Error: Request  was completed with errors.
+          CA has exausted all available serial numbers
+          EOF
+
+          diff expected stderr
 
       - name: Enroll a cert when request range is exhausted
         run: |
@@ -673,52 +876,38 @@ jobs:
           docker exec secondary pki-server ca-cert-request-find | tee output
           sed -n "s/^ *Request ID: *\(.*\)$/\1/p" output > actual
 
-          # there should be 14 requests
-          seq 1 7 > expected
+          # there should be 15 requests
+          seq 1 9 > expected
           seq 16 20 >> expected
-          seq 8 9 >> expected
+          echo 10 >> expected
 
           diff expected actual
 
-      ####################################################################################################
-      # Enroll a cert when cert range is exhausted
-
-      - name: Enroll a cert when cert range is exhausted
-        run: |
-          docker exec primary pki \
-              -n caadmin \
-              ca-cert-issue \
-              --profile caUserCert \
-              --csr-file testuser.csr \
-              --output-file testuser.crt \
-              > >(tee stdout) 2> >(tee stderr >&2) || true
-
-          cat > expected << EOF
-          PKIException: Server Internal Error: Request  was completed with errors.
-          CA has exausted all available serial numbers
-          EOF
-
-          diff expected stderr
-
-      - name: Check requests
+      - name: Check certs
         if: always()
         run: |
-          docker exec primary pki-server ca-cert-request-find | tee output
-          sed -n "s/^ *Request ID: *\(.*\)$/\1/p" output > actual
+          docker exec primary pki-server ca-cert-find | tee output
+          sed -n "s/^ *Serial Number: *\(.*\)$/\1/p" output > actual
 
-          # there should be 15 requests
-          seq 1 7 > expected
-          seq 16 20 >> expected
-          seq 8 10 >> expected
+          # there should be 14 certs
+          seq 1 14 | while read n; do printf "0x%x\n" $n; done > expected
 
           diff expected actual
 
       ####################################################################################################
-      # Allocate new request range
+      # Allocate new ranges
 
       - name: Allocate new request range
         run: |
-          docker exec secondary pki -n caadmin ca-job-start serialNumberUpdate
+          docker exec primary pki \
+              -n caadmin \
+              ca-job-start \
+              serialNumberUpdate
+
+          docker exec secondary pki \
+              -n caadmin \
+              ca-job-start \
+              serialNumberUpdate
 
       - name: Enroll 10 certs in secondary CA
         run: |
@@ -746,9 +935,9 @@ jobs:
           sed -n "s/^ *Request ID: *\(.*\)$/\1/p" output > actual
 
           # there should be 25 requests
-          seq 1 7 > expected
+          seq 1 9 > expected
           seq 16 20 >> expected
-          seq 8 10 >> expected
+          echo 10 >> expected
           seq 21 30 >> expected
 
           diff expected actual
@@ -760,16 +949,10 @@ jobs:
           sed -n "s/^ *Serial Number: *\(.*\)$/\1/p" output > actual
 
           # there should be 24 certs
-          seq 1 24 | while read n; do printf "0x%x\n" $n; done > expected
+          seq 1 18 | while read n; do printf "0x%x\n" $n; done > expected
+          seq 49 54 | while read n; do printf "0x%x\n" $n; done >> expected
 
           diff expected actual
-
-      ####################################################################################################
-      # Allocate new cert range
-
-      - name: Allocate new cert range
-        run: |
-          docker exec primary pki -n caadmin ca-job-start serialNumberUpdate
 
       - name: Enroll 5 certs in primary CA
         if: always()
@@ -798,9 +981,9 @@ jobs:
           sed -n "s/^ *Request ID: *\(.*\)$/\1/p" output > actual
 
           # there should be 30 requests
-          seq 1 7 > expected
+          seq 1 9 > expected
           seq 16 20 >> expected
-          seq 8 10 >> expected
+          echo 10 >> expected
           seq 21 30 >> expected
           seq 11 15 >> expected
 
@@ -813,8 +996,8 @@ jobs:
           sed -n "s/^ *Serial Number: *\(.*\)$/\1/p" output > actual
 
           # there should be 29 certs
-          seq 1 24 | while read n; do printf "0x%x\n" $n; done > expected
-          seq 49 53 | while read n; do printf "0x%x\n" $n; done >> expected
+          seq 1 23 | while read n; do printf "0x%x\n" $n; done > expected
+          seq 49 54 | while read n; do printf "0x%x\n" $n; done >> expected
 
           diff expected actual
 
@@ -853,8 +1036,8 @@ jobs:
               | tee actual
 
           cat > expected << EOF
-          dbs.beginSerialNumber=31
-          dbs.endSerialNumber=42
+          dbs.beginSerialNumber=13
+          dbs.endSerialNumber=24
           dbs.serialCloneTransferNumber=9
           dbs.serialIncrement=12
           dbs.serialLowWaterMark=9
@@ -991,12 +1174,12 @@ jobs:
           SecurePort: 8443
           beginRange: 13
           endRange: 30
-          host: secondary.example.com
+          host: primary.example.com
 
           SecurePort: 8443
           beginRange: 31
           endRange: 48
-          host: primary.example.com
+          host: secondary.example.com
 
           EOF
 
@@ -1007,14 +1190,12 @@ jobs:
 
       - name: Allocate new ranges
         run: |
-          docker exec secondary pki \
-              -U https://primary.example.com:8443 \
+          docker exec primary pki \
               -n caadmin \
               ca-job-start \
               serialNumberUpdate
 
           docker exec secondary pki \
-              -U https://secondary.example.com:8443 \
               -n caadmin \
               ca-job-start \
               serialNumberUpdate
@@ -1054,8 +1235,8 @@ jobs:
               | tee actual
 
           cat > expected << EOF
-          dbs.beginSerialNumber=13
-          dbs.endSerialNumber=24
+          dbs.beginSerialNumber=31
+          dbs.endSerialNumber=42
           dbs.serialCloneTransferNumber=9
           dbs.serialIncrement=12
           dbs.serialLowWaterMark=9
@@ -1202,12 +1383,12 @@ jobs:
           SecurePort: 8443
           beginRange: 13
           endRange: 30
-          host: secondary.example.com
+          host: primary.example.com
 
           SecurePort: 8443
           beginRange: 31
           endRange: 48
-          host: primary.example.com
+          host: secondary.example.com
 
           EOF
 
