Add tests for KRA with Kryoptic

diff --git a/.github/workflows/kra-kryoptic-test.yml b/.github/workflows/kra-kryoptic-test.yml
--- a/.github/workflows/kra-kryoptic-test.yml
+++ b/.github/workflows/kra-kryoptic-test.yml
@@ -1,4 +1,4 @@
-name: KRA with HSM
+name: KRA with Kryoptic
 
 on: workflow_call
 
@@ -46,27 +46,81 @@ jobs:
               --network-alias=pki.example.com \
               pki
 
-      - name: Install dependencies
+      - name: Install Kryoptic
         run: |
-          docker exec pki dnf install -y softhsm opendnssec
+          # install OpenDNSSEC to ensure no conflicts
+          # https://github.com/dogtagpki/pki/issues/5045
+          docker exec pki dnf install -y kryoptic opensc opendnssec
 
-      - name: Create SoftHSM token
-        run: |
-          # allow PKI user to access SoftHSM files
-          docker exec pki usermod pkiuser -a -G ods
+          docker exec pki rpm -ql kryoptic
+          docker exec pki cat /usr/share/p11-kit/modules/kryoptic.module
 
-          # create SoftHSM token for PKI server
-          docker exec pki runuser -u pkiuser -- \
-              softhsm2-util \
-              --init-token \
-              --label HSM \
-              --so-pin Secret.HSM \
-              --pin Secret.HSM \
-              --free
+          # check with OpenSC
+          # NOTE: the command fails if there's no token
+          docker exec pki pkcs11-tool \
+              --module /usr/lib64/pkcs11/libkryoptic_pkcs11.so \
+              --show-info || true
 
-          docker exec pki ls -laR /var/lib/softhsm/tokens
+          # check with OpenSC
+          # NOTE: the command fails if there's no token
+          docker exec pki pkcs11-tool \
+              --module /usr/lib64/pkcs11/libkryoptic_pkcs11.so \
+              --list-slots || true
 
+          # check with NSS
           docker exec pki modutil -nocertdb -list
+
+      # https://github.com/dogtagpki/pki/wiki/Kryoptic
+      - name: Create Kryoptic token
+        run: |
+          # create password file for HSM
+          echo "Secret.HSM" > password.hsm
+
+          # configure token
+          docker exec pki runuser -u pkiuser -- \
+              mkdir -p /home/pkiuser/.config/kryoptic
+
+          docker exec -i pki runuser -u pkiuser -- \
+              tee /home/pkiuser/.config/kryoptic/token.conf << EOF
+          [[slots]]
+          slot = 1
+          dbtype = "sqlite"
+          dbargs = "/home/pkiuser/.config/kryoptic/token.sql"
+          EOF
+
+          # check with OpenSC
+          docker exec pki runuser -u pkiuser -- \
+              pkcs11-tool \
+              --module /usr/lib64/pkcs11/libkryoptic_pkcs11.so \
+              --list-slots
+
+          # initialize token and SO PIN
+          docker exec pki runuser -u pkiuser -- \
+              pkcs11-tool \
+              --module /usr/lib64/pkcs11/libkryoptic_pkcs11.so \
+              --label HSM \
+              --so-pin $(cat password.hsm) \
+              --init-token
+
+          # initialize user PIN
+          docker exec pki runuser -u pkiuser -- \
+              pkcs11-tool \
+              --module /usr/lib64/pkcs11/libkryoptic_pkcs11.so \
+              --login \
+              --login-type so \
+              --so-pin $(cat password.hsm) \
+              --pin $(cat password.hsm) \
+              --init-pin
+
+          # check with OpenSC
+          docker exec pki runuser -u pkiuser -- \
+              pkcs11-tool \
+              --module /usr/lib64/pkcs11/libkryoptic_pkcs11.so \
+              --list-slots
+
+          # check with NSS
+          docker exec pki runuser -u pkiuser -- \
+              modutil -nocertdb -list
 
       - name: Install CA with HSM
         run: |
@@ -82,14 +136,15 @@ jobs:
               -D pki_ocsp_signing_token=HSM \
               -D pki_audit_signing_token=HSM \
               -D pki_subsystem_token=HSM \
-              -D pki_sslserver_token=internal \
+              -D pki_sslserver_token=HSM \
               -v
 
       - name: Check system certs in internal token
         run: |
-          # CA should create 5 certs in internal token
-          echo "5" > expected
-          docker exec pki pki \
+          # CA should create 0 certs
+          echo "0" > expected
+          docker exec pki runuser -u pkiuser -- \
+              pki \
               -d /var/lib/pki/pki-tomcat/conf/alias \
               nss-cert-find | tee output
           grep "Serial Number:" output | wc -l > actual
@@ -97,9 +152,10 @@ jobs:
 
       - name: Check system certs in HSM
         run: |
-          # CA should create 4 certs in HSM
-          echo "4" > expected
-          docker exec pki pki \
+          # CA should create 5 certs
+          echo "5" > expected
+          docker exec pki runuser -u pkiuser -- \
+              pki \
               -d /var/lib/pki/pki-tomcat/conf/alias \
               -f /var/lib/pki/pki-tomcat/conf/password.conf \
               --token HSM \
@@ -121,75 +177,38 @@ jobs:
               -D pki_transport_token=HSM \
               -D pki_audit_signing_token=HSM \
               -D pki_subsystem_token=HSM \
-              -D pki_sslserver_token=internal \
-              -v
+              -D pki_sslserver_token=HSM \
+              --debug \
+              > >(tee stdout) 2> >(tee stderr >&2)
+
+      - name: Check for warnings
+        if: always()
+        run: |
+          sed -n '/^WARNING:/p' stderr | tee output
+          wc -l output
+
+      - name: Check external commands
+        if: always()
+        run: |
+          sed -n '/^DEBUG: Command:/p' stderr | tee output
+          wc -l output
 
       - name: Check system certs in internal token
         run: |
-          # KRA should create 3 additional certs in internal token
-          echo "8" > expected
-          docker exec pki pki \
+          echo "0" > expected
+          docker exec pki runuser -u pkiuser -- \
+              pki \
               -d /var/lib/pki/pki-tomcat/conf/alias \
               nss-cert-find | tee output
           grep "Serial Number:" output | wc -l > actual
           diff expected actual
 
-      - name: Check kra_storage cert in internal token
-        run: |
-          echo ",," > expected
-          docker exec pki pki \
-              -d /var/lib/pki/pki-tomcat/conf/alias \
-              nss-cert-show \
-              kra_storage | tee output
-          sed -n 's/\s*Trust Flags:\s*\(\S\+\)\s*$/\1/p' output > actual
-          diff expected actual
-
-          docker exec pki pki \
-              -d /var/lib/pki/pki-tomcat/conf/alias \
-              -f /var/lib/pki/pki-tomcat/conf/password.conf \
-              nss-cert-verify \
-              --cert-usage SSLClient \
-              kra_storage
-
-      - name: Check kra_transport cert in internal token
-        run: |
-          echo ",," > expected
-          docker exec pki pki \
-              -d /var/lib/pki/pki-tomcat/conf/alias \
-              nss-cert-show \
-              kra_transport | tee output
-          sed -n 's/\s*Trust Flags:\s*\(\S\+\)\s*$/\1/p' output > actual
-          diff expected actual
-
-          docker exec pki pki \
-              -d /var/lib/pki/pki-tomcat/conf/alias \
-              -f /var/lib/pki/pki-tomcat/conf/password.conf \
-              nss-cert-verify \
-              --cert-usage SSLClient \
-              kra_transport
-
-      - name: Check kra_audit_signing cert in internal token
-        run: |
-          echo ",,P" > expected
-          docker exec pki pki \
-              -d /var/lib/pki/pki-tomcat/conf/alias \
-              nss-cert-show \
-              kra_audit_signing | tee output
-          sed -n 's/\s*Trust Flags:\s*\(\S\+\)\s*$/\1/p' output > actual
-          diff expected actual
-
-          docker exec pki pki \
-              -d /var/lib/pki/pki-tomcat/conf/alias \
-              -f /var/lib/pki/pki-tomcat/conf/password.conf \
-              nss-cert-verify \
-              --cert-usage ObjectSigner \
-              kra_audit_signing
-
       - name: Check system certs in HSM
         run: |
           # KRA should create 3 additional certs in HSM
-          echo "7" > expected
-          docker exec pki pki \
+          echo "8" > expected
+          docker exec pki runuser -u pkiuser -- \
+              pki \
               -d /var/lib/pki/pki-tomcat/conf/alias \
               -f /var/lib/pki/pki-tomcat/conf/password.conf \
               --token HSM \
@@ -200,7 +219,8 @@ jobs:
       - name: Check kra_storage cert in HSM
         run: |
           echo "u,u,u" > expected
-          docker exec pki pki \
+          docker exec pki runuser -u pkiuser -- \
+              pki \
               -d /var/lib/pki/pki-tomcat/conf/alias \
               -f /var/lib/pki/pki-tomcat/conf/password.conf \
               --token HSM \
@@ -209,7 +229,8 @@ jobs:
           sed -n 's/\s*Trust Flags:\s*\(\S\+\)\s*$/\1/p' output > actual
           diff expected actual
 
-          docker exec pki pki \
+          docker exec pki runuser -u pkiuser -- \
+              pki \
               -d /var/lib/pki/pki-tomcat/conf/alias \
               -f /var/lib/pki/pki-tomcat/conf/password.conf \
               nss-cert-verify \
@@ -219,7 +240,8 @@ jobs:
       - name: Check kra_transport cert in HSM
         run: |
           echo "u,u,u" > expected
-          docker exec pki pki \
+          docker exec pki runuser -u pkiuser -- \
+              pki \
               -d /var/lib/pki/pki-tomcat/conf/alias \
               -f /var/lib/pki/pki-tomcat/conf/password.conf \
               --token HSM \
@@ -228,7 +250,8 @@ jobs:
           sed -n 's/\s*Trust Flags:\s*\(\S\+\)\s*$/\1/p' output > actual
           diff expected actual
 
-          docker exec pki pki \
+          docker exec pki runuser -u pkiuser -- \
+              pki \
               -d /var/lib/pki/pki-tomcat/conf/alias \
               -f /var/lib/pki/pki-tomcat/conf/password.conf \
               nss-cert-verify \
@@ -238,7 +261,8 @@ jobs:
       - name: Check kra_audit_signing cert in HSM
         run: |
           echo "u,u,Pu" > expected
-          docker exec pki pki \
+          docker exec pki runuser -u pkiuser -- \
+              pki \
               -d /var/lib/pki/pki-tomcat/conf/alias \
               -f /var/lib/pki/pki-tomcat/conf/password.conf \
               --token HSM \
@@ -247,7 +271,8 @@ jobs:
           sed -n 's/\s*Trust Flags:\s*\(\S\+\)\s*$/\1/p' output > actual
           diff expected actual
 
-          docker exec pki pki \
+          docker exec pki runuser -u pkiuser -- \
+              pki \
               -d /var/lib/pki/pki-tomcat/conf/alias \
               -f /var/lib/pki/pki-tomcat/conf/password.conf \
               nss-cert-verify \
@@ -255,11 +280,14 @@ jobs:
               HSM:kra_audit_signing
 
       - name: Run PKI healthcheck
+        if: false
         run: docker exec pki pki-healthcheck --failures-only
 
       - name: Check admin cert
         run: |
-          docker exec pki pki-server cert-export ca_signing --cert-file ca_signing.crt
+          docker exec pki pki-server cert-export \
+              --cert-file ca_signing.crt \
+              ca_signing
 
           docker exec pki pki nss-cert-import \
               --cert ca_signing.crt \
@@ -277,15 +305,31 @@ jobs:
           docker exec pki pki -n caadmin kra-user-show kraadmin
 
       - name: Remove KRA
-        run: docker exec pki pkidestroy -s KRA -v
+        run: |
+          docker exec pki pkidestroy \
+              -s KRA \
+              --debug \
+              > >(tee stdout) 2> >(tee stderr >&2)
+
+      - name: Check for warnings
+        if: always()
+        run: |
+          sed -n '/^WARNING:/p' stderr | tee output
+          wc -l output
+
+      - name: Check external commands
+        if: always()
+        run: |
+          sed -n '/^DEBUG: Command:/p' stderr | tee output
+          wc -l output
 
       - name: Remove CA
         run: docker exec pki pkidestroy -s CA -v
 
-      - name: Remove SoftHSM token
+      - name: Remove Kryoptic token
         run: |
-          docker exec pki ls -laR /var/lib/softhsm/tokens
-          docker exec pki runuser -u pkiuser -- softhsm2-util --delete-token --token HSM
+          docker exec pki runuser -u pkiuser -- \
+              rm -rf /home/pkiuser/.config/kryoptic
 
       - name: Check for PKI core dumps
         if: failure()
@@ -307,4 +351,3 @@ jobs:
         if: always()
         run: |
           docker exec pki find /var/lib/pki/pki-tomcat/logs/kra -name "debug.*" -exec cat {} \;
- 
